import moment from 'moment';

export const airports = [
  { name: 'Pune', code: 'PNQ' },
  { name: 'Rajasthan', code: 'RAJ' },
  { name: 'Delhi', code: 'DEL' }
];

export const flights = [
  {
    type: 'one-way',
    id: 1,
    flight_code: 'PD - 202',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5000,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 121,
    flight_code: 'PQ - 272',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5500,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 123,
    flight_code: 'PA - 152',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5750,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 2,
    flight_code: 'AZ - 201',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 7000,
    duration: '1h 55m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 3,
    flight_code: 'EF - 203',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 9000,
    duration: '1h 55m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 390,
    flight_code: 'EF - 203',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 12000,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 33,
    flight_code: 'EF - 203',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 13000,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 37,
    flight_code: 'EF - 203',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 14500,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 300,
    flight_code: 'RE - 204',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 10500,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 12,
    flight_code: 'ER - 901',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 13500,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1122,
    flight_code: 'ER - 901',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 14500,
    duration: '2h 10m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 142,
    flight_code: 'ER - 901',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 11500,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 152,
    flight_code: 'ER - 901',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 12500,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 20,
    flight_code: 'QW - 284',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 14000,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 145,
    flight_code: 'RT - 504',
    origin: 'Pune',
    destination: 'Rajasthan',
    fare: 16000,
    duration: '2h 05m',
    departureDate: moment().format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1000,
    flight_code: 'PD - 670',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5000,
    duration: '2h 05m',
    departureDate: moment().add('1', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('1', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1001,
    flight_code: 'PD - 109',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 10000,
    duration: '2h 05m',
    departureDate: moment().add('1', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('1', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1002,
    flight_code: 'PD - 560',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 15000,
    duration: '2h 05m',
    departureDate: moment().add('1', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('1', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1003,
    flight_code: 'PD - 212',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5000,
    duration: '2h 05m',
    departureDate: moment().add('2', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1004,
    flight_code: 'PD - 321',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 7000,
    duration: '2h 05m',
    departureDate: moment().add('2', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1005,
    flight_code: 'PD - 435',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 10000,
    duration: '2h 05m',
    departureDate: moment().add('2', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1006,
    flight_code: 'PD - 126',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 12000,
    duration: '2h 05m',
    departureDate: moment().add('2', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1007,
    flight_code: 'PD - 901',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 14000,
    duration: '2h 05m',
    departureDate: moment().add('2', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('2', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1008,
    flight_code: 'PD - 870',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5000,
    duration: '2h 05m',
    departureDate: moment().add('3', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('3', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1009,
    flight_code: 'PD - 456',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 7000,
    duration: '2h 05m',
    departureDate: moment().add('3', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('3', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1010,
    flight_code: 'PD - 327',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 11000,
    duration: '2h 05m',
    departureDate: moment().add('3', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('3', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1011,
    flight_code: 'PD - 420',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 15000,
    duration: '2h 05m',
    departureDate: moment().add('3', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('3', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1012,
    flight_code: 'PD - 440',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 5200,
    duration: '2h 05m',
    departureDate: moment().add('4', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('4', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1013,
    flight_code: 'PD - 450',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 7000,
    duration: '2h 05m',
    departureDate: moment().add('4', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('4', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1014,
    flight_code: 'PD - 450',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 7000,
    duration: '2h 05m',
    departureDate: moment().add('4', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('4', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1015,
    flight_code: 'PD - 127',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 11000,
    duration: '2h 05m',
    departureDate: moment().add('4', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('4', 'days').add('2', 'hours')
  },
  {
    type: 'one-way',
    id: 1016,
    flight_code: 'PD - 098',
    origin: 'Pune',
    destination: 'Delhi',
    fare: 14000,
    duration: '2h 05m',
    departureDate: moment().add('4', 'days').format('DD MM YYYY'),
    arrivalTime: moment().add('4', 'days').add('2', 'hours')
  },
  {
    type: 'return',
    id: 5,
    route_one_code: 'LH - 961',
    route_two_code: 'LH - 870',
    origin: 'Pune',
    destination: 'Delhi',
    route_one_fare: 5000,
    route_two_fare: 5000,
    route_one_departure: moment().add(1, 'hours'),
    route_one_arrival: moment().add(3, 'hours'),
    route_two_departure: moment().add(7, 'hours'),
    route_two_arrival: moment().add(8, 'hours'),
    departureDate: moment().format('DD MM YYYY'),
    returnDate: moment().add('1', 'days').format('DD MM YYYY'),
    route_one_duration: '2h 10m',
    route_two_duration: '1h 55m'
  },
  {
    type: 'return',
    id: 6,
    route_one_code: 'EA - 512',
    route_two_code: 'EA - 640',
    origin: 'Pune',
    destination: 'Delhi',
    route_one_fare: 6500,
    route_two_fare: 6500,
    route_one_departure: moment().add(2, 'hours'),
    route_one_arrival: moment().add(4, 'hours'),
    route_two_departure: moment().add(8, 'hours'),
    route_two_arrival: moment().add(9, 'hours'),
    departureDate: moment().format('DD MM YYYY'),
    returnDate: moment().add('1', 'days').format('DD MM YYYY'),
    route_one_duration: '2h 10m',
    route_two_duration: '1h 55m'
  },
  {
    type: 'return',
    id: 7,
    route_one_code: 'RT - 412',
    route_two_code: 'RT - 530',
    origin: 'Pune',
    destination: 'Delhi',
    route_one_fare: 8000,
    route_two_fare: 9000,
    route_one_departure: moment().add(3, 'hours'),
    route_one_arrival: moment().add(5, 'hours'),
    route_two_departure: moment().add(9, 'hours'),
    route_two_arrival: moment().add(10, 'hours'),
    departureDate: moment().format('DD MM YYYY'),
    returnDate: moment().add('1', 'days').format('DD MM YYYY'),
    route_one_duration: '2h 10m',
    route_two_duration: '1h 55m'
  },
  {
    type: 'return',
    id: 8,
    route_one_code: 'QA - 127',
    route_two_code: 'QA - 960',
    origin: 'Pune',
    destination: 'Rajasthan',
    route_one_fare: 9000,
    route_two_fare: 9000,
    route_one_departure: moment().add(4, 'hours'),
    route_one_arrival: moment().add(5, 'hours'),
    route_two_departure: moment().add(8, 'hours'),
    route_two_arrival: moment().add(9, 'hours'),
    departureDate: moment().format('DD MM YYYY'),
    returnDate: moment().add('1', 'days').format('DD MM YYYY'),
    route_one_duration: '2h 10m',
    route_two_duration: '1h 55m'

  },
  {
    type: 'return',
    id: 340,
    route_one_code: 'QA - 127',
    route_two_code: 'QA - 960',
    origin: 'Pune',
    destination: 'Rajasthan',
    route_one_fare: 9500,
    route_two_fare: 9500,
    route_one_departure: moment().add(4, 'hours'),
    route_one_arrival: moment().add(5, 'hours'),
    route_two_departure: moment().add(8, 'hours'),
    route_two_arrival: moment().add(9, 'hours'),
    departureDate: moment().format('DD MM YYYY'),
    returnDate: moment().add('1', 'days').format('DD MM YYYY'),
    route_one_duration: '2h 10m',
    route_two_duration: '1h 55m'
  }
];
